# Generated by Django 3.2 on 2023-12-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='price',
            name='open_next',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
