# Generated by Django 4.2.7 on 2023-12-24 00:03

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC"),
        ),
    ]
