# Generated by Django 4.2.7 on 2023-12-18 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("open", models.FloatField(blank=True, default=0.0, null=True)),
                ("close", models.FloatField(blank=True, default=0.0, null=True)),
                ("high", models.FloatField(blank=True, default=0.0, null=True)),
                ("low", models.FloatField(blank=True, default=0.0, null=True)),
                ("ask", models.FloatField(blank=True, default=0.0, null=True)),
                ("bid", models.FloatField(blank=True, default=0.0, null=True)),
                ("volume", models.FloatField(blank=True, default=0.0, null=True)),
                ("open_next", models.FloatField(blank=True, default=0.0, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickers.ticker"
                    ),
                ),
            ],
            options={
                "get_latest_by": "date",
            },
        ),
    ]
